- name: Creat dir local cri-docker 
  ansible.builtin.file:
    path: /usr/local/bin/cri-docker
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Creat dir cri-docker 
  ansible.builtin.file:
    path: /usr/bin/cri-docker
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Install local cri-docker
  ansible.builtin.git:
    repo: https://github.com/Mirantis/cri-dockerd.git
    dest: /usr/local/bin/cri-docker
    clone: true
    version: master
- name: Install cri-docker
  ansible.builtin.git:
    repo: https://github.com/Mirantis/cri-dockerd.git
    dest: /usr/bin/cri-docker
    clone: true
    version: master
- name: Copy cri-docker.service
  ansible.builtin.copy:
    remote_src: true
    src: /usr/local/bin/cri-docker/packaging/systemd/cri-docker.service
    dest: /etc/systemd/system/cri-docker.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
- name: Copy cri-docker.socket
  ansible.builtin.copy:
    remote_src: true
    src: /usr/local/bin/cri-docker/packaging/systemd/cri-docker.socket
    dest: /etc/systemd/system/cri-docker.socket
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Systemctl reload
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: cri-docker.service
- name: Enable cri-docker
  ansible.builtin.shell: systemctl enable --now cri-docker.service
- name: Add Google SDK

# coppy script
# tasks file for k8s
- name: Copy cri-dockerd script
  ansible.builtin.copy:
    src: cri-dockerd.sh
    dest: /home/ubuntu/cri-dockerd.sh
    owner: root
    group: root
    mode: "777"
- name: Run cri-dockerd script
  ansible.builtin.script:
    cmd: /home/ubuntu/cri-dockerd.sh
    