---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: crawler
    component: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: crawler
        component: mongo
    spec:
    # Создаём контейнер с Монгой
      containers:
        - image: mongo
          name: mongo
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
# Создаём PersistentVolume
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: service-mongo
  labels:
    app: crawler
    component: mongo
spec:
# Открываем порты, по которым будем работать с Монгой
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: crawler
    component: mongo
