apiVersion: v1
kind: Service
metadata:
  name: service-mongo
  labels:
    app: crawler
    component: mongo
spec:
# Открываем порты, по которым будем работать с Монгой
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: crawler
    component: mongo
