---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deploy
  labels:
    app: crawler
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: ui
  template:
    metadata:
      # name: ui-pod
      labels:
        app: crawler
        component: ui
    spec:
      containers:
        # для деплоя созданного контейнера
        - name: crawler-ui
          # yamllint disable-line rule:line-length
          # image: cr.yandex/crpdjaf8gfis0d6k905r/coolerwhite/search_engine_ui:__VERSION__
          image: cr.yandex/crpdjaf8gfis0d6k905r/coolerwhite/search_engine_ui:1fe0f385
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-ui
  labels:
    app: crawler
    component: ui
spec:
  selector:
    app: crawler
    component: ui
  ports:
    - name: app-listener
      protocol: TCP
      # Port load balancer
      port: 80
      # Port POD
      targetPort: 8000
  type: LoadBalancer
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: autoscaling-ui
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: ui
#   minReplicas: 1
#   maxReplicas: 3
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50
