---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  persistentVolumeReclaimPolicy: Recycle
