---
- name: Run cri-dockerd
  block:
    - name: Wget tar
      ansible.builtin.unarchive:
        src: https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.4/cri-dockerd-0.3.4.amd64.tgz
        dest: /usr/local/bin/
        remote_src: true
    - name: Download cri-docker.service
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.service
        dest: /etc/systemd/system/
        remote_src: true
    - name: Download cri-docker.socket
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.socket
        dest: /etc/systemd/system/
        remote_src: true
    - name: Make simlink cri-docker.service
      ansible.builtin.replace:
        path: /etc/systemd/system/cri-docker.service
        regexp: /usr/bin/cri-dockerd
        replace: /usr/local/bin/cri-dockerd
    - name: Systemctl reload
      ansible.builtin.systemd:
        daemon_reload: true
        enabled: true
        name: cri-docker.service
    - name: Enable cri-docker
      ansible.builtin.command: systemctl enable --now cri-docker.service
- name: Add repo and Key
  block:
    - name: Add key
      ansible.builtin.script: add_key.sh --some-arguments 1234
    - name: Add repo
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
        filename: kubernetes.list
    - name: Udate cache
      ansible.builtin.apt:
        update_cache: true
- name: Install kublet kubeadm kubectl
  ansible.builtin.apt:
    pkg:
      - kublet
      - kubeadm
      - kubectl
- name: Hold kublet
  ansible.builtin.dpkg_selections:
    name: kublet
    selection: hold
- name: Hold kubeadm
  ansible.builtin.dpkg_selections:
    name: kubeadm
    selection: hold
- name: Hold kubectl
  ansible.builtin.dpkg_selections:
    name: kubectl
    selection: hold
